runtime: python
env: flex
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app
instance_class: F4

runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "3.10"
- uses: azure/webapps-deploy@v2
  with:
    publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
 - name: Setup Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.x
